INSERT INTO prodotto(categoria_id, nome, descrizione, prezzo, quantita_inventario)
VALUES
    (1, "Red Bull Original",
     "Classic energy drink with caffeine, taurine and B vitamins. Crisp, lightly carbonated and designed to provide a quick energy boost.",
     2.20, 50),
    (1, "Monster Energy Original",
     "The iconic Monster formula featuring a bold citrus flavor, high caffeine content and an energizing blend of vitamins.",
     2.50, 40),
    (1, "Rockstar Original",
     "A classic energy drink with a sweet flavor profile, caffeine and taurine, ideal for long workdays or intense workouts.",
     2.30, 35),
    (1, "Burn Original",
     "Burn Original combines caffeine and guarana with a smooth sweet taste to deliver long-lasting energy.",
     2.10, 35),
    (1, "Hell Classic",
     "Hell Energy Drink Classic offers a balanced combination of caffeine and B vitamins with a refreshing citrus flavor.",
     1.80, 70),
    (1, "Relentless Origin",
     "A full-bodied energy drink with a rich flavor and a strong caffeine kick, perfect for demanding days.",
     2.40, 50),
    (1, "NOS Original",
     "American-style energy drink with a citrus-forward taste and an energizing formula designed for maximum performance.",
     2.60, 50),
    (1, "Reign Total Body Fuel",
     "High-performance energy drink containing caffeine, B vitamins and electrolytes with zero sugar.",
     2.80, 20),
    (1, "C4 Energy",
     "Pre-workout inspired energy drink with caffeine and performance-focused ingredients for enhanced focus and endurance.",
     2.90, 30),
    (1, "Bang Energy",
     "Zero-sugar energy drink packed with caffeine and essential vitamins for sustained energy throughout the day.",
     2.90, 40),
    (1, "Prime Energy",
     "Modern energy drink combining caffeine with coconut water and vitamins for a refreshing boost.",
     2.70, 32),
    (1, "Celsius Sparkling",
     "Fitness-oriented energy drink featuring caffeine from natural sources and a refreshing sparkling taste.",
     2.80, 21),
    (1, "Guru Organic Energy",
     "Organic energy drink made with naturally sourced caffeine from green tea and guarana.",
     2.90, 15);

INSERT INTO prodotto(categoria_id, nome, descrizione, prezzo, quantita_inventario)
VALUES
    (2, "Red Bull Sugarfree",
     "All the energy of the original Red Bull with no sugar and the same refreshing taste.",
     2.30, 11),
    (2, "Monster Ultra White",
     "A sugar-free Monster with a light citrus flavor and the signature Monster energy blend.",
     2.60, 20),
    (2, "Monster Ultra Paradise",
     "Refreshing kiwi, lime and cucumber inspired flavor with zero sugar and high caffeine.",
     2.60, 37),
    (2, "Monster Ultra Fiesta Mango",
     "Tropical mango flavored energy drink with zero sugar and a smooth finish.",
     2.60, 30),
    (2, "Rockstar Zero Carb",
     "Zero carbohydrate energy drink delivering caffeine and vitamins without added sugar.",
     2.40, 22),
    (2, "Hell Zero",
     "Sugar-free version of Hell Energy with the same balanced flavor and caffeine content.",
     1.90, 25),
    (2, "Burn Zero",
     "The classic Burn experience with no added sugar and a refreshing carbonated taste.",
     2.20, 35);

INSERT INTO prodotto(categoria_id, nome, descrizione, prezzo, quantita_inventario)
VALUES
    (3, "Monster Mango Loco",
     "Juicy mango-inspired energy drink with tropical fruit flavors and the classic Monster energy blend.",
     2.70,25),
    (3, "Monster Pipeline Punch",
     "A vibrant mix of passion fruit, orange and guava flavors combined with Monster's signature formula.",
     2.70,24),
    (3, "Red Bull Summer Edition",
     "Limited edition Red Bull featuring a refreshing seasonal fruit flavor while maintaining the classic energy formula.",
     2.80,30),
    (3, "Monster Pacific Punch",
     "Fruit punch flavored energy drink inspired by tropical blends and packed with caffeine.",
     2.80,18),
    (3, "Red Bull Blue Edition",
     "Blueberry flavored Red Bull delivering the same energy formula with a fruity twist.",
     2.60,37);